### ISSUE TITLE
is it me or the code?

### ISSUE THREAD

**Issue by paragon1006** [MattMuelot/PyChatGUI#2]
this happened
![error2](https://user-images.githubusercontent.com/109076963/178252021-9947effd-7c15-4621-9eac-3980e0b28c08.png)
![error](https://user-images.githubusercontent.com/109076963/178252029-b82b0bdf-b160-4063-8938-faa58fac68cf.png)

**Comment by VeinyAngus** [comment]
Hey friend I'm not at my computer but I'll take a look at this issue as soon as i get home

**Comment by paragon1006** [comment]
thanks

**Comment by VeinyAngus** [comment]
hey so question, when you're entering the ip/port how are you formatting it? i should have probably clarified (and this will definitely be a fix i work on) but when you enter the ip/port it needs to be formatted as `192.168.1.211/PORT`

now obviously the port and ip depends on how you configure the server but as default it runs off port 50505

**Comment by paragon1006** [comment]
Thanks I'll try that out today

**Comment by VeinyAngus** [comment]
yeah please let me know as soon as you can if that fixes the issue

**Comment by paragon1006** [comment]
![image](https://user-images.githubusercontent.com/109076963/178447938-fbb0f312-7e47-42f7-b102-63e92ddbc523.png)

**Comment by paragon1006** [comment]
works now, thanks

**Comment by paragon1006** [comment]
![IMG-20220712-WA0001.jpg](https://user-images.githubusercontent.com/109076963/178468128-b309255c-f593-4784-9d60-14afd9a8dc2b.jpg)

**Comment by paragon1006** [comment]
I entered Port and ip correctly

**Comment by VeinyAngus** [comment]
Congratulations! I'm going to set this as resolved
